services:
  minio: # Object storage
    image: 'minio/minio'
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
  postgres: # Main database
    image: postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: MSNcars
  keycloak: # Authorization server
    image: 'bitnami/keycloak'
    ports:
      - '8081:8081'
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KEYCLOAK_DATABASE_PORT: 5432
      KEYCLOAK_DATABASE_USER: admin
      KEYCLOAK_DATABASE_PASSWORD: admin
      KEYCLOAK_DATABASE_NAME: MSNcars
      KEYCLOAK_HTTP_PORT: 8081
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KEYCLOAK_DATABASE_HOST: postgres
      KEYCLOAK_EXTRA_ARGS: --import-realm
    depends_on:
      - postgres
    volumes: # Mount configuration file
      - ./src/main/resources/keycloak:/opt/bitnami/keycloak/data/import